### ISSUE TITLE
Not Allowed access when we have different domains (POST)

### ISSUE THREAD

**Issue by luistduarte** [reTHINK-project/dev-catalogue#60] opened 2017-03-03 16:28 UTC
when i use postman it gives me the right answer.
![screenshot from 2017-03-03 16 05 58](https://cloud.githubusercontent.com/assets/11315256/23559023/ab267282-002d-11e7-8ae5-f83e9a3df775.png)

But when i use one App with different domain, access is not permitted because we have differente domains (localhost and catalogue.localhost domains)
![screenshot from 2017-03-03 16 05 32](https://cloud.githubusercontent.com/assets/11315256/23559147/f69534c4-002d-11e7-8b29-ce927dcf3294.png)

We are sending POST request throught this [way](https://github.com/reTHINK-project/dev-hyperty-toolkit/blob/fix-forwar-msg/resources/browser/Request.js#L93-L96)

**Comment by Endebert** [comment] 2017-03-03 18:57
I did some testing, and I think I found the cause of the problem. But I will have to investigate it further.

What I can tell you is this: The cause of the error comes from the headers you add to the request, i.e.: 
```
xhr.setRequestHeader('content-type', 'application/json');
xhr.setRequestHeader('cache-control', 'no-cache');
```

Send the request without those headers and it works. I can't tell you why, though.

From what I can observe, I believe the request reaches the Broker, and I think the Broker automatically rejects it before it reaches my code. But I will have to spend some time figuring out why.

When adding the headers in Postman and then sending the request, it still get's a response, so something strange is going on.

As a quick fix, please simply comment out the request headers mentioned above and you should be good for now.

**Comment by luistduarte** [comment] 2017-03-06 11:25
Thanks Robert, but after this i get another error, seems like catalogue is not prepared for make POST request method on `https://catalogue.localhost/.well-known/sourcepackage/GroupChatManager`, 
![screenshot from 2017-03-06 11 22 12](https://cloud.githubusercontent.com/assets/11315256/23608073/7ebee1b4-025f-11e7-92e9-42190fab027c.png)

**Comment by emmelmann-fokus** [comment] 2017-03-07 13:30
Hi @pchainho ,

Robert will contact you directly to suggest a date / time for an integration session.

**Comment by Endebert** [comment] 2017-03-07 16:06
@luistduarte Sorry for the late response. This is a bug in RuntimeCatalogue of dev-service-framework. It tries to get the sourcePackage with the same constraints, which can't succeed.

I pushed a fix into a new branch called `sourcepackage_fix`. Please try it and tell me if it solves the problem.

Based on your feedback (i.e. if there are still problems), I will try to make time for a call on Thursday.

**Comment by luistduarte** [comment] 2017-03-07 17:24
yes, there are still problems.. but it is a different one. `POST https://catalogue.localhost/.well-known/protocolstub/default/cguid 500 (Server Error)`

I used this command for start catalogue-broker: `command: [-host, 'catalogue.localhost', -default, protocolstub/VertxProtoStub, -default, protocolstub/VertxProtoStubNode]`

Testing on Postman it works for this url: `POST https://catalogue.localhost/.well-known/protocolstub/default` and it gives me the right protostub depending on constraints sent

**Closed** 2017-03-20 11:57 UTC
